version: '3'
services:
    ads:
        build: .
        container_name: ads
        environment:
            COMPOSER_VERSION: 1
        networks:
            - proxy
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.ads.rule=Host(`ads-apm.dev.local`)"
            - "traefik.http.routers.ads.tls=true"
        volumes:
            - ".:/app"
    ads_elk:
        image: elasticsearch:5
        container_name: ads_elk
        volumes:
            - ads_data:/usr/share/elasticsearch/data
        environment:
            - discovery.type=single-node
            - network.host=0.0.0.0
            - discovery.seed_hosts=0.0.0.0
        networks:
            - proxy

volumes:
    ads_data:

networks:
    proxy:
        external: true
