version: '3'
services:
    ads:
        image: adimeotech/adimeo-data-suite:5.6
        container_name: ads
        environment:
            COMPOSER_VERSION: 1
        networks:
            - adimeo-net
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.ads.rule=Host(`ads.dev.local`)"
            - "traefik.http.routers.ads.tls=true"
        volumes:
            - ".:/app"
    ads_elk:
        image: elasticsearch:5
        container_name: ads_elk
        volumes:
            - ads_data:/usr/share/elasticsearch/data
        environment:
            - discovery.type=single-node
            - network.host=0.0.0.0
            - discovery.seed_hosts=0.0.0.0
        networks:
            - adimeo-net

volumes:
    ads_data:

networks:
    adimeo-net:
        external: true
